name: codacy-coverage-reporter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        ./gradlew test
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml